name: Deploy Octopus to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Configure AWS credentials using your GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3) Log into Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4) Build and push Docker image to ECR
      - name: Build and push Docker image to ECR
        run: |
          # Use commit SHA as an image tag
          IMAGE_TAG=latest

          # Construct the ECR URI from your secrets
          ECR_URI="665040277244.dkr.ecr.us-east-1.amazonaws.com/octopus-deploy"

          # Build the image from your Dockerfile
          docker build -t octopus-deploy .

          # Tag it for ECR
          docker tag octopus-deploy:latest "665040277244.dkr.ecr.us-east-1.amazonaws.com/octopus-deploy:latest"

          # Push the image to ECR
          docker push "665040277244.dkr.ecr.us-east-1.amazonaws.com/octopus-deploy:latest"

      # 5) Render (update) the ECS task definition
      #    - Overwrites the container image field
      #    - Injects secrets for DB connection & admin password as ENV variables
      - name: Render ECS task definition
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # Base ECS task definition JSON
          task-definition: ecs-task-definition.json

          # The container name to update in "containerDefinitions"
          container-name: octopus-container

          # Use the newly pushed image
          image: 665040277244.dkr.ecr.us-east-1.amazonaws.com/octopus-deploy:latest

          # Override environment variables with your RDS/Octopus secrets
          environment-variables: >
            OCTOPUS_SQL_CONNECTION_STRING=_
